#! /bin/sh

#fix cursor
xsetroot -cursor_name left_ptr


bspc monitor ^1 -d i ii iii iv v vi vii viii ix
bspc monitor ^2 -d m

bspc config border_width         1

if xrandr | grep " connected" | grep -qv "LVDS" ; then     #non-laptop monitor is being used
    bspc config window_gap 10

else
    bspc config window_gap          12

fi

pgrep lemonbar && bspc config top_padding 18


bspc config split_ratio          0.48
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config initial_polarity     second_child


#don't manage these
bspc rule -a 9menu:* manage=off



#default: pseudotile all
bspc rule -a *:* state=pseudo_tiled



#make these float



#put these somewhere
bspc rule -a Signal desktop='^8' follow=off focus=off
bspc rule -a Thunderbird desktop='^2'



#tile these

bspc rule -a 'Deezloader Remix':* state=tiled
bspc rule -a Emacs:emacs state=tiled
bspc rule -a firefox:* state=tiled
bspc rule -a Mumble:mumble state=tiled
bspc rule -a Rocket.Chat:rocket.chat state=tiled
bspc rule -a Signal state=tiled
bspc rule -a Surf state=tiled
bspc rule -a URxvt:urxvt state=tiled
bspc rule -a Xournalpp state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Zoom state=tiled



bspc config initial_polarity     second_child
	



#make these float
bspc rule -a Pinentry-gtk-2:\* state=floating





# general settings
bspc config pointer_modifier mod1


bspc config external_rules_command ~/.config/bspwm/ext.sh
