#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
if xrandr | grep " connected" | grep -qv "LVDS" ; then
    #non-laptop monitor is being used
    bspc config window_gap 18
else
    bspc config window_gap          14
fi


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#todo: pseudotile if there's another window; tile if first window in desktop
bspc rule -a *:* state=pseudo_tiled

bspc rule -a 9menu:* state=floating
bspc rule -a Emacs:emacs state=tiled
bspc rule -a firefox:* state=tiled
bspc rule -a Signal desktop='^8' follow=off focus=off
bspc rule -a Surf state=tiled
bspc rule -a Thunderbird desktop='^6'
bspc rule -a Zathura:org.pwmt.zathura state=tiled
